services:
  dvr:
    image: ghcr.io/prodYakkai/srs-dvr:main
    ports:
    - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/data # Or wherever you mount srs's dvr path
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:5000/ping || exit 1
      interval: 60s
      timeout: 30s
      retries: 5