[project]
name = "srs-dvr-azure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-storage-blob>=12.23.1",
    "boto3>=1.35.69",
    "flask>=3.0.3",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.0.1",
]
